using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using AutoTagger.Configuration;
using Emby.Web.GenericEdit;
using MediaBrowser.Common;
using MediaBrowser.Common.Plugins;
using MediaBrowser.Controller.Library;
using MediaBrowser.Controller.Plugins;
using MediaBrowser.Model.Drawing;
using MediaBrowser.Model.Entities;
using MediaBrowser.Model.Logging;
using MediaBrowser.Model.Plugins;

namespace AutoTagger
{
    /// <summary>
    /// Auto Tagger plugin entry point.
    /// </summary>
    /// <remarks>
    /// Emby differences from the Jellyfin build of this plugin:
    /// <list type="bullet">
    /// <item>The settings page is generated by the server from <see cref="PluginOptions"/>.
    /// Jellyfin serves a hand-written HTML page with an inline script; Emby's equivalent route
    /// (IHasWebPages plus an embedded configPage.html) is the pre-4.x style and does not render
    /// correctly on a current server, so this plugin derives from BasePluginSimpleUI instead.</item>
    /// <item>The plugin id must be returned from an overridden <see cref="Id"/> property.
    /// Jellyfin's BasePlugin declares it abstract; Emby's declares it virtual.</item>
    /// <item>Emby has no equivalent of Jellyfin's IPluginServiceRegistrator, so there is
    /// no DI registration file in this project.</item>
    /// <item>The dashboard icon comes from IHasThumbImage (an embedded resource stream),
    /// not from a manifest imagePath as it does with jprm on Jellyfin.</item>
    /// </list>
    /// </remarks>
    public class Plugin : BasePluginSimpleUI<PluginOptions>, IHasThumbImage
    {
        private readonly Guid _id = new Guid("ddd2f8f0-cd06-41a9-a5c2-2b6e54160596");

        private readonly ILibraryManager _libraryManager;
        private readonly ILogger _logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="Plugin"/> class.
        /// </summary>
        /// <param name="applicationHost">The application host, required by BasePluginSimpleUI to
        /// register the settings page and its options store.</param>
        /// <param name="libraryManager">The library manager, used to list libraries when the
        /// settings page is opened.</param>
        /// <param name="logManager">The log manager, supplied by Emby.</param>
        public Plugin(IApplicationHost applicationHost, ILibraryManager libraryManager, ILogManager logManager)
            : base(applicationHost)
        {
            Instance = this;
            _libraryManager = libraryManager;
            _logger = logManager.GetLogger("AutoTagger");
        }

        /// <summary>
        /// Gets the current plugin instance.
        /// </summary>
        public static Plugin Instance { get; private set; }

        /// <inheritdoc />
        public override string Name
        {
            get { return "Auto Tagger"; }
        }

        /// <inheritdoc />
        public override string Description
        {
            get
            {
                return "Applies configured tags to media as it is added to selected libraries. " +
                       "Useful for tag-based parental controls, where a user policy allows or blocks content by tag.";
            }
        }

        /// <inheritdoc />
        public override Guid Id
        {
            get { return _id; }
        }

        /// <summary>
        /// Gets the current settings.
        /// </summary>
        /// <remarks>
        /// BasePluginSimpleUI keeps GetOptions protected. The rest of the plugin reads its
        /// configuration through this property, which is the direct replacement for the
        /// <c>Configuration</c> property that BasePlugin&lt;TConfiguration&gt; used to supply.
        /// </remarks>
        public PluginOptions Configuration
        {
            get { return GetOptions(); }
        }

        /// <inheritdoc />
        public ImageFormat ThumbImageFormat
        {
            get { return ImageFormat.Png; }
        }

        /// <inheritdoc />
        public Stream GetThumbImage()
        {
            var type = GetType();
            return type.Assembly.GetManifestResourceStream(type.Namespace + ".thumb.png");
        }

        /// <summary>
        /// Rebuilds the editable rows from the server's current library list just before the
        /// settings page is shown, seeding each one from the stored rule for that library.
        /// </summary>
        /// <param name="options">The stored options.</param>
        /// <returns>The options to display.</returns>
        /// <remarks>
        /// Building the rows here rather than storing them is what keeps the page honest: a library
        /// added or renamed since the last save shows up correctly, and a rule can never refer to a
        /// library that no longer exists.
        /// </remarks>
        protected override PluginOptions OnBeforeShowUI(PluginOptions options)
        {
            if (options == null)
            {
                return base.OnBeforeShowUI(null);
            }

            var stored = options.Rules ?? new LibraryTagRule[0];

            options.LibraryRules = RuleRows.Build(_libraryManager.GetVirtualFolders(), stored);

            _logger.Info("Auto Tagger settings page opened with {0} libraries and {1} stored rules", options.LibraryRules.Count, stored.Length);

            return base.OnBeforeShowUI(options);
        }

        /// <summary>
        /// Folds the edited rows back into the stored rules.
        /// </summary>
        /// <param name="options">The options being saved.</param>
        /// <returns>Whether the save should proceed.</returns>
        protected override bool OnOptionsSaving(PluginOptions options)
        {
            if (options == null)
            {
                return base.OnOptionsSaving(null);
            }

            // A save that carries no rows at all is not an instruction to delete every rule — it
            // means the page posted something this build did not expect. Keep what is stored.
            if (options.LibraryRules == null)
            {
                _logger.Error("Auto Tagger received a save with no library rows; keeping the stored rules unchanged");

                var current = GetOptions();
                options.Rules = current == null ? new LibraryTagRule[0] : current.Rules;

                return base.OnOptionsSaving(options);
            }

            options.Rules = RuleRows.ToRules(options.LibraryRules);

            _logger.Info("Auto Tagger saved {0} library rules", options.Rules.Length);

            return base.OnOptionsSaving(options);
        }

        /// <inheritdoc />
        protected override void OnCreatePageInfo(PluginPageInfo pageInfo)
        {
            pageInfo.Name = Name;
            pageInfo.DisplayName = Name;

            base.OnCreatePageInfo(pageInfo);
        }

    }
}
